### ISSUE TITLE
EROARE MEN MILDRINKIO

### ISSUE THREAD

**Issue by rol3x1337** [developer60-stack/v3#5]
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6e47d1, 0x16)
        /usr/lib/go-1.11/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc02c000000, 0x4000000, 0x9128b8)
        /usr/lib/go-1.11/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x8f95c0, 0x4000000, 0x0, 0x0)
        /usr/lib/go-1.11/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(Killed

ITS A ME MILDRINKIO KUM FAKEM IE YEROARE DAYA NEBUNA

**Comment by developer60-stack** [comment]
La ce versiune primesti eroarea?

**Comment by rol3x1337** [comment]
v3-3.1.2

**Comment by developer60-stack** [comment]
S-a rezolvat.
